version: '3.8'

services:
  redis:
    build: './src/redis'
    ports:
      - '6379:6379'

  postgres:
    build: './src/postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  waha:
    build: './src/waha'
    ports:
      - '3000:3000'
    volumes:
      - 'waha_sessions:/app/.sessions'
      - 'waha_media:/app/.media'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  n8n:
    build: './src/n8n'
    ports:
      - '5678:5678'
    volumes:
      - 'n8n_data:/home/node/.n8n'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  pgdata:
  waha_sessions:
  waha_media:
  n8n_data:
