version: '3.8'

services:

  waha:
    build: './src/waha'
    ports:
      - '3000:3000'
    volumes:
      - 'waha_sessions:/app/.sessions'
      - 'waha_media:/app/.media'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  n8n:
    build: './src/n8n'
    ports:
      - '5678:5678'
    volumes:
      - 'n8n_data:/home/node/.n8n'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
